channels:
- conda-forge

platforms:
- linux-64
- osx-arm64

dependencies:
- python >=3.9.6
- pip >=21.1.3

- click >=8.0.1
- conda-lock >=0.11.0
- ensureconda >=1.4.1
- ruamel.yaml >=0.17.10

- yapf >=0.31.0
